### PR TITLE
Preview: Use gogoproto instead of default golang protobuf library

### PR DESCRIPTION
**Pull request by owais**

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Requires https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/73

**Comment by tigrannajaryan** [comment]
@bogdandrutu please have a look. I believe this nicely satisfies the requirements that you had and will allow replacing gogoproto with official protobuf package by simple rewriting of import paths.

**Comment by owais** [comment]
Also needs: https://github.com/census-instrumentation/opencensus-proto/pull/203

**Comment by pjanotti** [comment]
It wasn't intended to be merged but just to show an approach to the issue. Closing it.

**Pull request closed without merging**
