### PR TITLE
Remove unused factory files

### PR DESCRIPTION
**Pull request by tigrannajaryan**
This is dead code that is not used anywhere.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
I think the code https://github.com/open-telemetry/opentelemetry-service/blob/master/factories/factories.go should replace these files. A package called "factories" is too generic and does not make too much sense.

**Comment by tigrannajaryan** [comment]
@bogdandrutu I agree. I plan to split factories into 3 parts (exporter, receiver, processor) and move each to corresponding package. It will be a separate PR.

**Comment by bogdandrutu** [comment]
Please update the branch :)

**Comment by bogdandrutu** [comment]
This is causing us to miss a deadline, I did not realize you removed the entire observability we added for all the receivers/exporters.

**Comment by songy23** [comment]
We have observability for tracing receivers and exporters:
https://github.com/open-telemetry/opentelemetry-service/blob/100a230c5cadf8fed5497faae209f8007399e06f/observability/observability.go#L91-L125

However none of the metrics receivers/exporters have it, IIRC.

**Pull request merged**
