### PR TITLE
Use Factory instead of ReceiverFactory when package contains receiver

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Already sent for exporters https://github.com/open-telemetry/opentelemetry-service/pull/123 :). I need to submit first https://github.com/open-telemetry/opentelemetry-service/pull/119 before I will do for processor.

**Comment by tigrannajaryan** [comment]
@bogdandrutu are you planning to set a record for PRs done in one day? :-)

**Comment by bogdandrutu** [comment]
This is how I work when I don't have meetings :))) Luckly for the community I have a lot of meetings :))))

**Comment by tigrannajaryan** [comment]
>This is how I work when I don't have meetings :))) Luckly for the community I have a lot of meetings :))))

I need to try to save the community and schedule a few meetings with you for the next week :-)

**Pull request merged**
