### PR TITLE
Refactore: using add-attributes as typeStr

### PR DESCRIPTION
**Pull request by MohamedElqdusy**
As discussed [here](https://github.com/open-telemetry/opentelemetry-service/pull/152#discussion_r303931449)

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@MohamedElqdusy I think you also need to fix the processor name https://github.com/open-telemetry/opentelemetry-service/blob/master/defaults/defaults_test.go

**Comment by tigrannajaryan** [comment]
This implements https://github.com/open-telemetry/opentelemetry-service/issues/164
Please mention in commit message.

**Comment by tigrannajaryan** [comment]
I suggest that commit message instead of
```
Refactore: using add-attributes as typeStr
```
is
```
Use "add-attributes" as the name for addattributeprocessor
```

(Inspired by: https://chris.beams.io/posts/git-commit/)

**Comment by pjanotti** [comment]
Please rebase to fix the build issue.

**Pull request closed without merging**
