### PR TITLE
Rename package internal to common

### PR DESCRIPTION
**Pull request by ccaraman**
Due to Golang Special Packages, `internal` is only useable within this code base. However, there are critical functions like `TimeToTimestamp` or `GetAvailableLocalAddress` that should be available to all code bases that extend OpenTelemetry Service.  By renaming it to `common`, it is usable by all code bases. 

This PR has no observable code changes other than renaming the package.

### CODE REVIEW

**Comment by ccaraman** [comment]
@songy23 - We are working on a telemetry extension (first in our repository) to export telemetry to backends so we will be needing access to those functions as well.

**Comment by ccaraman** [comment]
What about `utils` instead of `common`? My philosophy around it is we should have top level components at the root ( receivers, service, config, utils) then do grouping underneath that. Otherwise the root will get pretty murky.

**Comment by bogdandrutu** [comment]
I don't personally think it is a good idea to export public everything. We need to keep them backwards compatible so I don't think it is a good idea. Also time to timestamp I think should be a proto util library.

**Comment by ccaraman** [comment]
I disagree - these are common utils used all over our code base and set a coding pattern/functions that ideally we'd want used in extensions/modifications/forks of this code base.  Ex: Modifications/extensions of Otel already exist (such as [contrib](https://github.com/open-telemetry/opentelemetry-service-contrib)) will have to rewrite internal functions soon enough.

I view there being two sets of interactions with this code base:
- Code contributors that are extending/modifying functionality either in our repository or some other. We should aim to enable developers to do the correct thing easily and reuse as many of our components as possible. This reduces the number of bugs, duplicated code and improves developer iteration. 
- Binary consumers - The two sets of interfaces are the parameters to the binary and the config. This is the interface that I believe we should analyze/protect and which we do a very good job at. Making the internal package public doesn't impact the binary that is built directly from this code base and will not impact our customers.

Making some of our core logic/helper functions internal doesn't stop bad code from getting out there. However, it does make it harder to do the right thing.

Re backwards compatibility:
In general as a code base we need to make commitments around what we want the story to be. Ex: No util breaking changes unless major version updates etc. We should take this into account with everything we do. That being said, as unfortunate as it is chances are we will have breaking changes across major versions or releases. However, I don't see that as being a full blocker for the stated benefits above.

**Comment by bogdandrutu** [comment]
I also think a lot of things can be kept internal. I do not understand the motivation to expose everything.

Sorry this is -1 for me the way how it is now blindly expose all the internals.

**Comment by ccaraman** [comment]
@bogdandrutu please be more specific about what you think should stay internal and address the points made in previous comments that way we can continue to make progress on this pr. :)

**Comment by bogdandrutu** [comment]
So from your description:
TimeToTimestamp -> we should not write our own and we should use this https://github.com/golang/protobuf/blob/master/ptypes/timestamp.go#L113
GetAvailableLocalAddress -> I can see this to be useful, if that is the case that you need to use this please move it in some public package.

I think it is good to have a clear separation between what we expose public (which means we have to maintain backwards compatibility) vs what is public because it is an internal package that we share.

**Comment by pjanotti** [comment]
> I'm going to close this PR ...

Actually closing it...

**Pull request closed without merging**
