### PR TITLE
Imports new Prometheus receiver from OpenCensus.

### PR DESCRIPTION
**Pull request by dinooliva**
We'd like to use the new Prometheus receiver with the OpenTelemetry agent.

### CODE REVIEW

**Comment by songy23** [comment]
Please fix CLA and run `GO111MODULE=on go mod tidy`.

**Comment by dinooliva** [comment]
Note: This code is copied from the original pull request to opencensus-service: https://github.com/census-instrumentation/opencensus-service/pull/572

**Comment by dinooliva** [comment]
CLA signed.

**Comment by tigrannajaryan** [comment]
@dinooliva this changes looks incomplete to me. This requires fixing Preceiver creation in prometheusreceiver/factory.go to pass the logger. That in turn will require CreateMetricsReceiver() to accept the logger as a parameter.

While there I'd also make Preceiver creation via a proper New() function instead of constructing a struct to make sure any future changes to Preceiver construction cause compiler error.

**Pull request merged**
