### PR TITLE
Fixed ballast test cases by using  cross-platform lib

### PR DESCRIPTION
**Pull request by owais**
This should make the test work on the following platforms:

- FreeBSD i386/amd64/arm
- Linux i386/amd64/arm
- Windows/amd64
- Darwin i386/amd64
- OpenBSD amd64

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Strange that it show reduction in codecov. Also the build result does not seem to be reported from Travis to Github properly.

**Comment by owais** [comment]
@tigrannajaryan it had a typo `linu/amd64` instead of `linux` so the test case never ran :)

**Comment by owais** [comment]
## Update

The test was working across platforms but not so reliably on Travis CI. It seems the testsuite and the Go compiler toolchain consuming very different amount of memory across different environments. We could get it to work but I don't think it would be worth the effort especially considering it would likely break in new environments and we would have to maintain it. I think it's better to have this as a standalone test that spins up a production collector instance and monitor's it's memory usage. @pjanotti suggested we use the perf testbed for this and I think that makes a lot of sense. As a result this PR is just disabling the ballast test for now. We'll remove it once it is implemented as a perf test.

@tigrannajaryan @songy23

**Comment by owais** [comment]
I actually removed it completely to get rid of the dependency as there was no point in carrying it for nothing.

**Comment by tigrannajaryan** [comment]
>I think it's better to have this as a standalone test that spins up a production collector instance and monitor's it's memory usage. @pjanotti suggested we use the perf testbed for this and I think that makes a lot of sense.

I agree. This makes a lot of sense as an E2E test.

**Pull request merged**
