### PR TITLE
Added pkg directory to host importable packages

### PR DESCRIPTION
**Pull request by owais**
Added a new pkg sub-directory that hosts code intended to be imported by
3rd party packages.

Packages with `internal` in their import path cannot be imported by
other Go programs. This is enforced by the compiler. Some of the code
currently hosted by the internal director needs to be made available to
other programs so additional exporters, receivers and processors can be
easily implemented independently.

As an alternative to `/pkg` we can also move them to project root but a lot of packages there might add clutter. I'm fine with either approach.

### CODE REVIEW

**Comment by owais** [comment]
@songy23 done, thanks.

**Comment by bogdandrutu** [comment]
I think there was a long conversation about using pkg. And we decided to not do that.

**Comment by tigrannajaryan** [comment]
@bogdandrutu can you please point to the discussion or if you remember the arguments post here?

**Comment by bogdandrutu** [comment]
https://github.com/census-instrumentation/opencensus-service/pull/430

**Comment by tigrannajaryan** [comment]
@owais I tend to agree with some of the arguments against `pkg`. It looks superfluous to me and unnecessarily lengthens import path. With `internal` being the convention for stuff that is not for external use I think "every else is public" is not a bad rule.

I do not see much benefits in `pkg` provided that the public packages are properly and clearly organized. Perhaps this effort is better spent in cleaning up the package structure that we have, I think it could use some improvement.

I'd like to know what you think about this.

We probably need a broader discussion about code organization. I think the codebase could generally benefit from better organization (something along the clean architecture lines: https://medium.com/@eminetto/clean-architecture-using-golang-b63587aa5e3f - so a layered organization with one clear direction of dependencies).

**Comment by owais** [comment]
I don't have any strong preference for `pkg`. I thought it shows clear intent that the code inside is meant to be consumed by other projects. Totally fine if we want to invert that by treating `internal` as strictly private and everything else (probably except cmd) as public.

**Comment by bogdandrutu** [comment]
If you need the code to be "public" put it in a directory directly in the root project not in internal.

**Comment by tigrannajaryan** [comment]
My understanding is that `internal` is enforced by the compiler. You cannot import it from a code that is in a different tree. So you don't just treat it as private it is enforced to be private.

It then leaves everything else to be public. Even `cmd` I think is fine. If you have stuff that is exportable from `cmd` package I do not see a reason why it should not be possible (or be prohibited by convention) to import.

**Comment by owais** [comment]
I'll move it all outside but have a question about the config packages. We could move the config packages to the project root or we could create a `config` package at root and host `configmodels` and `configv2` inside it. So the structure would look like:

```
- config
    - v2
    - models
```

I like that everything related to config will be inside the config "container".

I don't like that the import path lies about the package name. I mean when importing `opentelemetry-service/config/v2`, the package would still be accessible in code with `configv2` which can be a bit surprising. We could change the package identifier to `v2` but that would make code importing the package more cryptic as it wouldn't be obvious what `v2` is when reading the code. 


### Option 1. 
```
- factories
- config
     - v2         // imported as configv2
     - models     // imported as configmodels
```

### Option 2.
```
- factories
- configv2 
- configmodels
```

Interested in hearing what everyone thinks.

**Comment by tigrannajaryan** [comment]
I would move _all_ models to a separate package. Granted, we currently have only config models but there can be more. I find that it is reasonable that models are a separate package. They are the glue that holds other packages together and they should be importable from any other package. At the same time other package should be more careful about importing each other.

So I would do this:
```
- cmd
- models (config models are here)
- factory (this can be split into 3 parts and go into the corresponding packages)
- configv2 (should be later renamed to config when cleaning up, maybe even now is the time)
- exporter
- receiver
- processor
- internal
```

**Comment by owais** [comment]
Moved out of `pkg` https://github.com/open-telemetry/opentelemetry-service/pull/73

**Pull request merged**
