### PR TITLE
Cache metric descriptors

### PR DESCRIPTION
**Pull request by dinooliva**
@songy23 @rghetia - ptal

Testing added to metricsbuilder_tests.go

### CODE REVIEW

**Comment by bogdandrutu** [comment]
With the current model this may not be correct, at the moment when the metricdescriptor may be created we may not have discovered all the label keys because they were not present in the first timeseries.

**Comment by dinooliva** [comment]
@bogdandrutu 

Yes, that's correct. The problem is that, even if the metric descriptor is cached, we have to verify that it contains the expected keys and update the cache if it doesn't, which may take away the benefits we get from having a cache.

Alternatively, we could index the cache by the metric name and keys but this makes for a larger cache and once again be nullify the benefits we get from the cache.

Thoughts?

**Comment by tigrannajaryan** [comment]
Same comment as 2 other PRs: please add a description that tells why the change is made and what problem it solves.

**Comment by dinooliva** [comment]
I'm going to close this for now and revisit it later.

**Pull request closed without merging**
